return {
    {
        ["name"] = "Medkit",
        ["shortname"] = "Medkit",
        ["filtername"] = "guy_medkit",
        ["hammerid"] = 4779729,
        ["buttonid"] = 4779723,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["pt_spawner"] = "firstaid_template",
    },
    {
        ["name"] = "Flamethrower",
        ["shortname"] = "Flamethrower",
        ["filtername"] = "flamethrower",
        ["hammerid"] = 6006413,
        ["buttonid"] = 6006399,
        ["energyname"] = "flame_counter",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMIN_REACHED,
        ["pt_spawner"] = "flame_temp",
    },
    {
        ["name"] = "Shotgun",
        ["shortname"] = "Shotgun",
        ["filtername"] = "shotgunname",
        ["hammerid"] = 4275139,
        ["buttonid"] = 4275224,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 5,
        ["cooldown"] = 2,
    },
    {
        ["name"] = "Knife",
        ["shortname"] = "Knife",
        ["filtername"] = "Knife_Owner",
        ["hammerid"] = 4287373,
        ["buttonid"] = 4287366,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "Weapon_Knife_Temp",
    },
}