return {
    {
        ["name"] = "C.A.T Launcher",
        ["shortname"] = "Launcher",
        ["filtername"] = "player_human_catlauncher",
        ["hammerid"] = 642407,
        ["buttonid"] = 642402,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 9,
        ["pt_spawner"] = "s_cat_launcher_rocketlauncher",
    },
    {
        ["name"] = "Laser Gun",
        ["shortname"] = "Laser",
        ["filtername"] = "player_human_lasergun",
        ["hammerid"] = 642904,
        ["buttonid"] = 642899,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 26,
        ["pt_spawner"] = "s_lasergun",
    },
    {
        ["name"] = "Plasma Cannon",
        ["shortname"] = "Plasma Cannon",
        ["filtername"] = "player_human_plasma",
        ["hammerid"] = 643392,
        ["buttonid"] = 643387,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 9,
        ["pt_spawner"] = "s_plasma_canon",
    },
    {
        ["name"] = "Medkit",
        ["shortname"] = "Medkit",
        ["filtername"] = "player_medkit",
        ["hammerid"] = 657036,
        ["buttonid"] = 657038,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 5,
        ["pt_spawner"] = "medkit_itemtemp",
    },
}