return {
    {
        ["name"] = "Wall",
        ["shortname"] = "Wall",
        ["filtername"] = "player_human_pyramid",
        ["hammerid"] = 9214,
        ["buttonid"] = 9218,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "human_pyramid_itemtemp",
    },
    {
        ["name"] = "Tornado",
        ["shortname"] = "Tornado",
        ["filtername"] = "player_human_tornado",
        ["hammerid"] = 9239,
        ["buttonid"] = 9241,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "human_tornado_itemtemp",
    },
    {
        ["name"] = "Ammo",
        ["shortname"] = "Ammo",
        ["filtername"] = "player_human_ammo",
        ["hammerid"] = 9200,
        ["buttonid"] = 9063,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "human_ammo_itemtemp",
    },
    {
        ["name"] = "Sand",
        ["shortname"] = "Sand",
        ["filtername"] = "player_human_sand",
        ["hammerid"] = 8983,
        ["buttonid"] = 8987,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "human_sand_itemtemp",
    },
    {
        ["name"] = "Heal",
        ["shortname"] = "Heal",
        ["filtername"] = "player_human_heal",
        ["hammerid"] = 8892,
        ["buttonid"] = 8896,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "human_heal_itemtemp",
    },
}