return {
    {
        ["name"] = "Soul Cube",
        ["shortname"] = "Cube",
        ["filtername"] = "cubdux1",
        ["hammerid"] = 2009,
        ["buttonid"] = 2003,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 12,
        ["pt_spawner"] = "garabuz1",
    },
    {
        ["name"] = "Rocket Launcher",
        ["shortname"] = "Launcher",
        ["filtername"] = "guypickeduprocketlauncher",
        ["hammerid"] = 2083,
        ["buttonid"] = 3538,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 6,
    },
    {
        ["name"] = "Electro Grenade",
        ["shortname"] = "Electro Nade",
        ["filtername"] = "grenades1",
        ["hammerid"] = 3135,
        ["buttonid"] = 3142,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 40,
    },
    {
        ["name"] = "Heal",
        ["shortname"] = "Heal",
        ["filtername"] = "oxx",
        ["hammerid"] = 3202,
        ["buttonid"] = 3200,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 40,
        ["pt_spawner"] = "heal_template",
    },
    {
        ["name"] = "Time Heart",
        ["shortname"] = "Heart",
        ["filtername"] = "oxx1",
        ["hammerid"] = 3309,
        ["buttonid"] = 3311,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
    },
    {
        ["name"] = "Pushgun",
        ["shortname"] = "Push",
        ["filtername"] = "oxx11",
        ["hammerid"] = 3320,
        ["buttonid"] = 3322,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 45,
    },
    {
        ["name"] = "Minigun",
        ["shortname"] = "Minigun",
        ["filtername"] = "krub1",
        ["hammerid"] = 3993,
        ["buttonid"] = 3988,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 10,
        ["cooldown"] = 13,
    },
    {
        ["name"] = "BFG",
        ["shortname"] = "BFG",
        ["buttonclass"] = "grenades1tru",
        ["filtername"] = "nagoi2",
        ["hammerid"] = 1520691,
        ["buttonid"] = 1520408,
        -- крч, видимо это баганая залупа вообще или только в gmod, а значит маппер даун
        --["mode"] = ENTWATCH_MODE_LIMITED_USES,
        --["maxuses"] = 7,
        --["cooldown"] = 15,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 15,
    },

    -- TODO: check ZM materias
    -- TODO2: ладно, они все сломаны. Скин физический, можно исправить через ShouldCollide
    {
        ["name"] = "Zombie Spider",
        ["shortname"] = "ZM Spider",
        ["filtername"] = "imps1",
        ["hammerid"] = 1900,
        ["buttonid"] = 1902,
        ["mode"] = ENTWATCH_MODE_SPAM_PROTECTION_ONLY,
    },
    {
        ["name"] = "Zombie Pinky",
        ["shortname"] = "ZM Pinky",
        ["filtername"] = "sobaka",
        ["hammerid"] = 1918,
        ["buttonid"] = 1919,
        ["mode"] = ENTWATCH_MODE_SPAM_PROTECTION_ONLY,
    },
    {
        ["name"] = "Zombie Mother Spider",
        ["shortname"] = "ZM Mother Spider",
        ["filtername"] = "pauchixaxx",
        ["hammerid"] = 1929,
        ["buttonid"] = 1934,
        ["mode"] = ENTWATCH_MODE_SPAM_PROTECTION_ONLY,
    },
    {
        ["name"] = "Zombie Skeleton",
        ["shortname"] = "ZM Skeleton",
        ["filtername"] = "skelets1",
        ["hammerid"] = 1938,
        ["buttonid"] = 1942,
        ["mode"] = ENTWATCH_MODE_SPAM_PROTECTION_ONLY,
    },
}