return {
    {
        ["name"] = "Wall Spawner",
        ["shortname"] = "Wall",
        ["filtername"] = "blockade",
        ["hammerid"] = 326008,
        ["buttonid"] = 325989,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 10,
        ["cooldown"] = 2,
        ["pt_spawner"] = "item_blockademaker",
    },
    {
        ["name"] = "Electro Gun",
        ["shortname"] = "Electro",
        ["filtername"] = "electric",
        ["hammerid"] = 326171,
        ["buttonid"] = 326315,
        ["energyname"] = "item_electric9",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMIN_REACHED,
        ["pt_spawner"] = "item_electricmaker",
    },
    {
        ["name"] = "EyeTech Launcher",
        ["shortname"] = "Launcher",
        ["filtername"] = "launcher",
        ["hammerid"] = 326586,
        ["buttonid"] = 326588,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 10,
        ["cooldown"] = 2,
        ["pt_spawner"] = "item_launchermaker",
    },
    {
        ["name"] = "Heal",
        ["shortname"] = "Heal",
        ["filtername"] = "heal",
        ["hammerid"] = 325974,
        ["buttonid"] = 325899,
        ["energyname"] = "item_heal7",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        ["cooldown"] = 60,
        ["pt_spawner"] = "item_healmaker",
        --["currentvalue"] = 1, -- sets to zero at stage 3 extreme
        --["hitmax"] = 2, -- max uses
    },
    {
        ["name"] = "Push Gun",
        ["shortname"] = "Push",
        ["filtername"] = "push",
        ["hammerid"] = 326086,
        ["buttonid"] = 326088,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 35,
        ["pt_spawner"] = "item_pushmaker",
    },
    {
        ["name"] = "Flamethrower",
        ["shortname"] = "Flame",
        ["filtername"] = "flamethrower",
        ["hammerid"] = 326332,
        ["buttonid"] = 326334,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 8,
        ["cooldown"] = 10,
        ["pt_spawner"] = "item_flamemaker",
    },
    {
        ["name"] = "Ammo",
        ["shortname"] = "Ammo",
        ["filtername"] = "ammowep",
        ["hammerid"] = 326492,
        ["buttonid"] = 326494,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "item_ammomaker",
    },
    {
        ["name"] = "Pipe Bomb",
        ["shortname"] = "Pipe Bomb",
        ["filtername"] = "pipe",
        ["hammerid"] = 326600,
        ["buttonid"] = 326602,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 5,
        ["cooldown"] = 1.5,
        ["pt_spawner"] = "item_pipemaker",
    },
    {
        ["name"] = "EyeTech Cannon",
        ["shortname"] = "Cannon",
        ["filtername"] = "cannon",
        ["hammerid"] = 326711,
        ["buttonid"] = 326713,
        ["mode"] = ENTWATCH_MODE_SPAM_PROTECTION_ONLY,
        ["pt_spawner"] = "item_cannonmaker",
    },
}