return {
    {
        ["name"] = "Bio",
        ["shortname"] = "Bio",
        ["hammerid"] = 2906432,
        ["buttonid"] = 2906364,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_bio_temp",
    },
    {
        ["name"] = "Barrier",
        ["shortname"] = "Barrier",
        ["hammerid"] = 2906517,
        ["buttonid"] = 2906449,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_barrier_temp",
    },
    {
        ["name"] = "Ultima",
        ["shortname"] = "Ultima",
        ["hammerid"] = 2906602,
        ["buttonid"] = 2906534,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 20,
        ["pt_spawner"] = "item_ultima_temp",
    },
    {
        ["name"] = "Wind",
        ["shortname"] = "Wind",
        ["hammerid"] = 2906834,
        ["buttonid"] = 2906766,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_wind_temp",
    },
    {
        ["name"] = "Heal",
        ["shortname"] = "Heal",
        ["hammerid"] = 2907132,
        ["buttonid"] = 2907064,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_heal_temp",
    },
    {
        ["name"] = "Ice",
        ["shortname"] = "Ice",
        ["hammerid"] = 2907354,
        ["buttonid"] = 2907286,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_ice_temp",
    },
    {
        ["name"] = "Aqua",
        ["shortname"] = "Aqua",
        ["hammerid"] = 2907705,
        ["buttonid"] = 2907637,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_water_temp",
    },
    {
        ["name"] = "Fire",
        ["shortname"] = "Fire",
        ["hammerid"] = 2907860,
        ["buttonid"] = 2907792,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_fire_temp",
    },
    {
        ["name"] = "Electro",
        ["shortname"] = "Electro",
        ["hammerid"] = 2908013,
        ["buttonid"] = 2907945,
        ["energyname"] = "item_electro_counter",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        ["hitmax"] = 1, -- max uses before cooldown
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_electro_temp",
    },
    {
        ["name"] = "Earth",
        ["shortname"] = "Earth",
        ["hammerid"] = 2908100,
        ["buttonid"] = 2908032,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_earth_temp",
    },
    {
        ["name"] = "Gravity",
        ["shortname"] = "Gravity",
        ["hammerid"] = 2908185,
        ["buttonid"] = 2908117,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_gravity_temp",
    },
    {
        ["name"] = "Mimic",
        ["shortname"] = "Mimic",
        ["hammerid"] = 4525325,
        ["buttonid"] = 4525251,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_mimic_temp",
    },
}