return {
    {
        ["name"] = "Cactuar Summon",
        ["shortname"] = "Cactuar",
        ["filtername"] = "cactus_Owner",
        ["hammerid"] = 11300536,
        ["buttonid"] = 11300523,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["pt_spawner"] = "Weapon_cactus_Temp",
    },
    {
        ["name"] = "King Bomb Summon",
        ["shortname"] = "Bomb",
        ["filtername"] = "bomb_Owner",
        ["hammerid"] = 11304097,
        ["buttonid"] = 11304099,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["pt_spawner"] = "Weapon_bomb_Temp",
    },
    {
        ["name"] = "Underworld Rod",
        ["shortname"] = "Rod",
        ["filtername"] = "drace001_Owner",
        ["hammerid"] = 11270633,
        ["buttonid"] = 11270624,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "Weapon_Edrace001_Temp",
    },
    {
        ["name"] = "Silver Mace",
        ["shortname"] = "Mace",
        ["filtername"] = "drace002_Owner",
        ["hammerid"] = 11272458,
        ["buttonid"] = 11272464,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 90,
        ["pt_spawner"] = "Weapon_Edrace002_Temp",
    },
    {
        ["name"] = "Chaos Blade",
        ["shortname"] = "Blade",
        ["filtername"] = "Chaos_Blade_Owner",
        ["hammerid"] = 11243956,
        ["buttonid"] = 11011477,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 2,
        ["cooldown"] = 75,
        ["pt_spawner"] = "Weapon_Chaos_Blade_Temp",
    },
}