return {
    {
        ["name"] = "Gravity",
        ["shortname"] = "Gravity",
        ["filtername"] = "portador_gravedad",
        ["hammerid"] = 1589,
        ["buttonid"] = 1587,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 55,
        ["pt_spawner"] = "ItemGravityTemp",
    },
    {
        ["name"] = "Electro",
        ["shortname"] = "Electro",
        ["filtername"] = "portador_electro",
        ["hammerid"] = 1546,
        ["buttonid"] = 1544,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 3,
        ["cooldown"] = 55,
        ["pt_spawner"] = "ItemElectroTemp",
    },
    {
        ["name"] = "Fire",
        ["shortname"] = "Fire",
        ["filtername"] = "portador_fire",
        ["hammerid"] = 1410,
        ["buttonid"] = 1422,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 55,
        ["pt_spawner"] = "ItemFireTemp",
    },
    {
        ["name"] = "Ice",
        ["shortname"] = "Ice",
        ["filtername"] = "portador_ice",
        ["hammerid"] = 1377,
        ["buttonid"] = 1398,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 55,
        ["pt_spawner"] = "ItemIceTemp",
    },
    {
        ["name"] = "Heal",
        ["shortname"] = "Heal",
        ["filtername"] = "portador_heal",
        ["hammerid"] = 1492,
        ["buttonid"] = 1494,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 50,
        ["pt_spawner"] = "ItemHealTemp",
    },
    {
        ["name"] = "Earth",
        ["shortname"] = "Earth",
        ["filtername"] = "portador_earth",
        ["hammerid"] = 1460,
        ["buttonid"] = 1463,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 55,
        ["pt_spawner"] = "ItemEarthTemp",
    },
    {
        ["name"] = "Wind",
        ["shortname"] = "Wind",
        ["filtername"] = "portador_viento",
        ["hammerid"] = 1434,
        ["buttonid"] = 1440,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 55,
        ["pt_spawner"] = "ItemWindTemp",
    },
    {
        ["name"] = "Ultima",
        ["shortname"] = "Ultima",
        ["filtername"] = "portador_ultima",
        ["hammerid"] = 1359,
        ["buttonid"] = 1364,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 20,
        ["pt_spawner"] = "ItemUltimaTemp",
    },
}