return {
    {
        ["name"] = "Gravity Materia",
        ["shortname"] = "Gravity",
        ["filtername"] = "Gravity_Owner",
        ["hammerid"] = 323441,
        ["buttonid"] = 323443,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "Item_Gravity_Temp1",
    },
    {
        ["name"] = "Electro Materia",
        ["shortname"] = "Electro",
        ["filtername"] = "Electro_Owner",
        ["hammerid"] = 323285,
        ["buttonid"] = 323354,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["maxuses"] = 2,
        ["cooldown"] = 60,
        ["pt_spawner"] = "Item_Electro_Temp1",
        --["energyname"] = "Item_Electro_Counter",
        --["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        --["currentvalue"] = 1,
        --["hitmax"] = 3, -- max uses = 2, because OnHitMax sets the value to 1
    },
    {
        ["name"] = "Fire Materia",
        ["shortname"] = "Fire",
        ["filtername"] = "Fire_Owner",
        ["hammerid"] = 323126,
        ["buttonid"] = 323128,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "Item_Fire_Temp",
    },
    {
        ["name"] = "Bio Materia",
        ["shortname"] = "Bio",
        ["filtername"] = "Bio_Owner",
        ["hammerid"] = 323363,
        ["buttonid"] = 323367,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "Item_Bio_Temp1",
    },
    {
        ["name"] = "Heal Materia",
        ["shortname"] = "Heal",
        ["filtername"] = "Heal_Owner",
        ["hammerid"] = 323052,
        ["buttonid"] = 323121,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "Item_Heal_Temp",
    },
    {
        ["name"] = "Earth Materia",
        ["shortname"] = "Earth",
        ["filtername"] = "Earth_Owner",
        ["hammerid"] = 323735,
        ["buttonid"] = 323737,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "Item_Earth_Temp1",
    },
    {
        ["name"] = "Wind Materia",
        ["shortname"] = "Wind",
        ["filtername"] = "Wind_Owner",
        ["hammerid"] = 323517,
        ["buttonid"] = 323519,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "Item_Wind_Temp",
    },
    {
        ["name"] = "Ultima Materia",
        ["shortname"] = "Ultima",
        ["filtername"] = "Ultima_Owner",
        ["hammerid"] = 323814,
        ["buttonid"] = 323816,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 1,
        ["cooldown"] = 15,
        ["pt_spawner"] = "Item_Ultima_Temp",
    },
    {
        ["name"] = "Sleep Materia",
        ["shortname"] = "Sleep",
        ["filtername"] = "Sleep_Owner",
        ["hammerid"] = 524758,
        ["buttonid"] = 524762,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "Item_Sleep_Temp1",
    },
    {
        ["name"] = "Zombie Ice Materia",
        ["shortname"] = "ZM Ice",
        ["filtername"] = "Ice_Z_Owner",
        ["hammerid"] = 1589580,
        ["buttonid"] = 1589574,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Z_Ice_Temp",
    },
    {
        ["name"] = "Zombie Fire Materia",
        ["shortname"] = "ZM Fire",
        ["filtername"] = "Fire_Z_Owner",
        ["hammerid"] = 1576012,
        ["buttonid"] = 1576006,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Z_Fire_Temp",
    },
    {
        ["name"] = "Zombie Poison Materia",
        ["shortname"] = "ZM Poison",
        ["filtername"] = "Poison_Z_Owner",
        ["hammerid"] = 2102221,
        ["buttonid"] = 2102228,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Z_Poison_Temp",
    },
    {
        ["name"] = "Zombie Cactus",
        ["shortname"] = "ZM Cactus",
        ["filtername"] = "CactusZM_Z_Owner",
        ["hammerid"] = 1446673,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
        ["pt_spawner"] = "CactusZM_Spawner_Zombies",
    },
    {
        ["name"] = "Zombie Confuse Materia",
        ["shortname"] = "ZM Confuse",
        ["filtername"] = "Confuse_Owner",
        ["hammerid"] = 3468411,
        ["buttonid"] = 3468276,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Item_Z_Confuse_itemtemp",
    },
    {
        ["name"] = "Phoenix Down",
        ["shortname"] = "Potion",
        ["filtername"] = "Potion_Owner",
        ["hammerid"] = 2576537,
        ["buttonid"] = 2576539,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 1,
        ["pt_spawner"] = "Potion_Temp",
    },
}