return {
    {
        ["name"] = "Wind Staff",
        ["shortname"] = "Wind",
        ["filtername"] = "Player_Staff_Wind",
        ["hammerid"] = 2666416,
        ["buttonid"] = 2666409,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "Temp_Wind",
    },
    {
        ["name"] = "Water Staff",
        ["shortname"] = "Water",
        ["filtername"] = "Player_Staff_Water",
        ["hammerid"] = 2665857,
        ["buttonid"] = 2665844,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "Temp_Water",
    },
    {
        ["name"] = "Heal Staff",
        ["shortname"] = "Heal",
        ["filtername"] = "Player_Staff_Heal",
        ["hammerid"] = 2666175,
        ["buttonid"] = 2666177,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "Temp_Heal",
    },
    {
        ["name"] = "Earth Staff",
        ["shortname"] = "Earth",
        ["filtername"] = "Player_Staff_Earth",
        ["hammerid"] = 2666253,
        ["buttonid"] = 2665924,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "Temp_Earth",
    },
    {
        ["name"] = "Fire Staff",
        ["shortname"] = "Fire",
        ["filtername"] = "Player_Staff_Fire",
        ["hammerid"] = 2665939,
        ["buttonid"] = 2666016,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "Temp_Fire",
    },
    {
        ["name"] = "Electro Staff",
        ["shortname"] = "Electro",
        ["filtername"] = "Player_Staff_Electro",
        ["hammerid"] = 2666329,
        ["buttonid"] = 2666341,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "Temp_Electro",
    },
    {
        ["name"] = "Holy Staff",
        ["shortname"] = "Holy",
        ["filtername"] = "Player_Staff_Holy",
        ["hammerid"] = 2666037,
        ["buttonid"] = 2666019,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 20,
        ["pt_spawner"] = "Temp_Holy",
    },
    {
        ["name"] = "Zombie Warp Magick",
        ["shortname"] = "ZM Warp",
        ["filtername"] = "Player_Knife_Warp",
        ["hammerid"] = 2666579,
        ["buttonid"] = 2666581,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 80,
        ["pt_spawner"] = "Temp_Warp",
    },
    {
        ["name"] = "Zombie Lure Magick",
        ["shortname"] = "ZM Lure",
        ["filtername"] = "Player_Knife_Lure",
        ["hammerid"] = 2665489,
        ["buttonid"] = 2665560,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 80,
        ["pt_spawner"] = "Temp_Lure",
    },
    {
        ["name"] = "Zombie Heal Magick",
        ["shortname"] = "ZM Heal",
        ["filtername"] = "Player_Knife_Heal",
        ["hammerid"] = 2667303,
        ["buttonid"] = 2667229,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 80,
        ["pt_spawner"] = "Temp_Zm_Heal",
    },
    {
        ["name"] = "Zombie Invisibility Magick",
        ["shortname"] = "ZM Invis",
        ["filtername"] = "Player_Knife_Invis",
        ["hammerid"] = 2666721,
        ["buttonid"] = 2666653,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 80,
        ["pt_spawner"] = "Temp_Invis",
    },
    {
        ["name"] = "Zombie Blind Magick",
        ["shortname"] = "ZM Blind",
        ["filtername"] = "Player_Knife_Blind",
        ["hammerid"] = 2665770,
        ["buttonid"] = 2665772,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 80,
        ["pt_spawner"] = "Temp_Blind",
    },
    {
        ["name"] = "Zombie Shield Magick",
        ["shortname"] = "ZM Shield",
        ["filtername"] = "Player_Knife_Shield",
        ["hammerid"] = 2666977,
        ["buttonid"] = 2666981,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 80,
        ["pt_spawner"] = "Temp_Shield",
    },
    {
        ["name"] = "Zombie Fire Magick",
        ["shortname"] = "ZM Fire",
        ["filtername"] = "Player_Knife_Fire",
        ["hammerid"] = 2708384,
        ["buttonid"] = 2708251,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 80,
        ["pt_spawner"] = "Temp_Firezm",
    },
    {
        ["name"] = "Zombie Frost Magick",
        ["shortname"] = "ZM Frost",
        ["filtername"] = "Player_Knife_Frost",
        ["hammerid"] = 2708451,
        ["buttonid"] = 2708520,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 80,
        ["pt_spawner"] = "Temp_Frost",
    },
}