return {
    {
        ["name"] = "Cactuar Summon",
        ["shortname"] = "Cactuar",
        ["filtername"] = "cactus_Owner",
        ["hammerid"] = 11300536,
        ["buttonid"] = 11300523,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["pt_spawner"] = "Weapon_cactus_Temp",
    },
    {
        ["name"] = "King Bomb Summon",
        ["shortname"] = "Bomb",
        ["filtername"] = "bomb_Owner",
        ["hammerid"] = 11304097,
        ["buttonid"] = 11304099,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["pt_spawner"] = "Weapon_bomb_Temp",
    },
    {
        ["name"] = "Underworld Rod",
        ["shortname"] = "Rod",
        ["filtername"] = "drace001_Owner",
        ["hammerid"] = 11270633,
        ["buttonid"] = 11270624,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "Weapon_Edrace001_Temp",
    },
    {
        ["name"] = "Silver Mace",
        ["shortname"] = "Mace",
        ["filtername"] = "drace002_Owner",
        ["hammerid"] = 11272458,
        ["buttonid"] = 11272464,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 90,
        ["pt_spawner"] = "Weapon_Edrace002_Temp",
    },
    {
        ["name"] = "Chaos Blade",
        ["shortname"] = "Blade",
        ["filtername"] = "Chaos_Blade_Owner",
        ["hammerid"] = 11243956,
        ["buttonid"] = 11011477,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "Weapon_Chaos_Blade_Temp",
    },
    {
        ["name"] = "HP Poison",
        ["shortname"] = "Poison",
        ["filtername"] = "HP_Potion_Owner",
        ["hammerid"] = 11087670,
        ["buttonid"] = 11087602,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["pt_spawner"] = "Weapon_HP_Potion_Temp",
    },
    {
        ["name"] = "Haste Poison",
        ["shortname"] = "Haste",
        ["filtername"] = "Speed_Potion_Owner",
        ["hammerid"] = 11091040,
        ["buttonid"] = 11090966,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["pt_spawner"] = "Weapon_Speed_Potion_Temp",
    },
    {
        ["name"] = "Sword of Kings",
        ["shortname"] = "Kings",
        ["filtername"] = "Sword_of_Kings_Owner",
        ["hammerid"] = 10359168,
        ["buttonid"] = 10359096,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["pt_spawner"] = "Weapon_Sword_of_Kings_Temp",
    },
    {
        ["name"] = "Betelgeuse",
        ["shortname"] = "Betelgeuse",
        ["filtername"] = "betelgeuse_Owner",
        ["hammerid"] = 10313659,
        ["buttonid"] = 10313661,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["pt_spawner"] = "Weapon_betelgeuse_Temp",
    },
    {
        ["name"] = "Gun Blade",
        ["shortname"] = "Gun Blade",
        ["filtername"] = "GunBlade_Owner",
        ["hammerid"] = 10221862,
        ["buttonid"] = 10121229,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 15,
        ["pt_spawner"] = "Weapon_GunBlade_Temp",
    },
    {
        ["name"] = "Sandstorm Magick",
        ["shortname"] = "Sand",
        ["filtername"] = "Sand_Owner",
        ["hammerid"] = 8495852,
        ["buttonid"] = 8495856,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "Weapon_sand_Temp",
    },
    {
        ["name"] = "Ensanguined Shield",
        ["shortname"] = "Shield",
        ["filtername"] = "Shield_Owner",
        ["hammerid"] = 8470005,
        ["buttonid"] = 8469927,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 2,
        ["cooldown"] = 75,
        ["pt_spawner"] = "Weapon_Shield_Temp",
        --["energyname"] = "Item_Shield_Counter",
        --["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        --["currentvalue"] = 0,
        --["hitmax"] = 2, -- max uses
    },
    {
        ["name"] = "Thunder Magick",
        ["shortname"] = "Thunder",
        ["filtername"] = "Electro_Owner",
        ["hammerid"] = 8472203,
        ["buttonid"] = 8472299,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "Weapon_Electro_Temp",
    },
    {
        ["name"] = "Heal Magick",
        ["shortname"] = "Heal",
        ["filtername"] = "Heal_Owner",
        ["hammerid"] = 8472207,
        ["buttonid"] = 8472215,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Heal_Temp",
    },
    {
        ["name"] = "Penetrator Crossbow",
        ["shortname"] = "Crossbow",
        ["filtername"] = "Crossbow_Owner",
        ["hammerid"] = 8445113,
        ["buttonid"] = 8445121,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 5,
        ["pt_spawner"] = "Weapon_Crossbow_Temp",
    },
    {
        ["name"] = "Ultimate Blade",
        ["shortname"] = "Blade",
        ["filtername"] = "Blade_Owner",
        ["hammerid"] = 8445761,
        ["buttonid"] = 8445961,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 2,
        ["cooldown"] = 60,
        ["pt_spawner"] = "Weapon_blade_Temp",
        --["energyname"] = "Item_Blade_Counter",
        --["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        --["currentvalue"] = 0,
        --["hitmax"] = 2, -- max uses
    },
    {
        ["name"] = "Zombie Fire Magick",
        ["shortname"] = "ZM Fire",
        ["filtername"] = "fire_Z_Owner",
        ["hammerid"] = 11417377,
        ["buttonid"] = 11417306,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Z_fire_Temp",
    },
    {
        ["name"] = "Zombie Mateus Spear",
        ["shortname"] = "ZM Spear",
        ["filtername"] = "Mateus_Spear_Z_Owner",
        ["hammerid"] = 11361504,
        ["buttonid"] = 11361429,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 80,
        ["pt_spawner"] = "Weapon_Z_Mateus_Spear_Temp",
    },
    {
        ["name"] = "Zombie Belias Spear",
        ["shortname"] = "ZM Spear",
        ["filtername"] = "Belias_Spear_Z_Owner",
        ["hammerid"] = 11061783,
        ["buttonid"] = 11061776,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 80,
        ["pt_spawner"] = "Weapon_Z_Belias_Spear_Temp",
    },
    {
        ["name"] = "Zombie Highway Star",
        ["shortname"] = "ZM Star",
        ["filtername"] = "Highway_Star_Z_Owner",
        ["hammerid"] = 11007167,
        ["buttonid"] = 11007174,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 2,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Z_Highway_Star_Temp",
        --["energyname"] = "Item_Z_Highway_Star_Counter",
        --["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        --["currentvalue"] = 0,
        --["hitmax"] = 2, -- max uses
    },
    {
        ["name"] = "Zombie Fear Magick",
        ["shortname"] = "ZM Fear",
        ["filtername"] = "Fear_Z_Owner",
        ["hammerid"] = 10529270,
        ["buttonid"] = 10528741,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Z_Fear_Temp",
    },
    {
        ["name"] = "Zombie Heal Magick",
        ["shortname"] = "ZM Heal",
        ["filtername"] = "Heal_Z_Owner",
        ["hammerid"] = 9066505,
        ["buttonid"] = 9066432,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Z_Heal_Temp",
    },
    {
        ["name"] = "Zombie Critical Exploiter",
        ["shortname"] = "ZM Exploiter",
        ["filtername"] = "Critical_Exploiter_Z_Owner",
        ["hammerid"] = 8743619,
        ["buttonid"] = 8743610,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Z_Critical_Exploiter_Temp",
    },
    {
        ["name"] = "Zombie Gravity Magick",
        ["shortname"] = "ZM Gravity",
        ["filtername"] = "Gravity_Z_Owner",
        ["hammerid"] = 8718688,
        ["buttonid"] = 8718675,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "Weapon_Z_Gravity_Temp",
    },
    {
        ["name"] = "Zombie Warp Magick",
        ["shortname"] = "ZM Warp",
        ["filtername"] = "Warp_Z_Owner",
        ["hammerid"] = 8721599,
        ["buttonid"] = 8721525,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Z_Warp_Temp",
    },
    {
        ["name"] = "Zombie Zargabaath Sword",
        ["shortname"] = "ZM Sword",
        ["filtername"] = "ZargabaathS_Z_Owner",
        ["hammerid"] = 8656701,
        ["buttonid"] = 8656689,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Z_ZargabaathS_Temp",
    },
    {
        ["name"] = "Zombie Bergan Blade",
        ["shortname"] = "ZM Blade",
        ["filtername"] = "BerganS_Z_Owner",
        ["hammerid"] = 8595605,
        ["buttonid"] = 8595534,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Z_BerganS_Temp",
    },
}