return {
    {
        ["name"] = "Heal Magick",
        ["shortname"] = "Heal",
        ["filtername"] = "Heal_Owner",
        ["hammerid"] = 29413,
        ["buttonid"] = 29484,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "Weapon_Heal_Temp",
    },
    {
        ["name"] = "Wind Magick",
        ["shortname"] = "Wind",
        ["filtername"] = "Wind_Owner",
        ["hammerid"] = 29972,
        ["buttonid"] = 29974,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "Weapon_Wind_Temp",
    },
    {
        ["name"] = "Dark Magick",
        ["shortname"] = "Dark",
        ["filtername"] = "Darkaga_Owner",
        ["hammerid"] = 29894,
        ["buttonid"] = 29896,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "Weapon_Darkaga_Temp",
    },
    {
        ["name"] = "Blizzard Magick",
        ["shortname"] = "Ice",
        ["filtername"] = "Blizzard_Owner",
        ["hammerid"] = 29814,
        ["buttonid"] = 29818,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "Weapon_Blizzard_Temp",
    },
    {
        ["name"] = "Electro Magick",
        ["shortname"] = "Electro",
        ["filtername"] = "Electro_Owner",
        ["hammerid"] = 29734,
        ["buttonid"] = 29803,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "Weapon_Electro_Temp",
    },
    {
        ["name"] = "Fire Magick",
        ["shortname"] = "Fire",
        ["filtername"] = "Fire_Owner",
        ["hammerid"] = 29491,
        ["buttonid"] = 29495,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "Weapon_Fire_Temp",
    },
    {
        ["name"] = "Zombie Warp Magick",
        ["shortname"] = "ZM Warp",
        ["filtername"] = "Warp_Z_Owner",
        ["hammerid"] = 30795,
        ["buttonid"] = 30724,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Z_Warp_Temp",
    },
    {
        ["name"] = "Zombie Dark Magick",
        ["shortname"] = "ZM Dark",
        ["filtername"] = "Darkaga_Z_Owner",
        ["hammerid"] = 30712,
        ["buttonid"] = 30641,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Z_Darkaga_Temp",
    },
    {
        ["name"] = "Zombie Fire Magick",
        ["shortname"] = "ZM Fire",
        ["filtername"] = "Fire_Z_Owner",
        ["hammerid"] = 30486,
        ["buttonid"] = 30488,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Z_Fire_Temp",
    },
    {
        ["name"] = "Zombie Heal Magick",
        ["shortname"] = "ZM Heal",
        ["filtername"] = "Heal_Z_Owner",
        ["hammerid"] = 30269,
        ["buttonid"] = 30201,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_Z_Heal_Temp",
    },
    {
        ["name"] = "Berserk Sword",
        ["shortname"] = "Sword",
        ["filtername"] = "Berserk_Owner",
        ["hammerid"] = 36679,
        ["buttonid"] = 36607,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 5,
        ["pt_spawner"] = "Weapon_Berserk_Temp",
    },
}