return {
    {
        ["name"] = "Bio Materia",
        ["shortname"] = "Bio",
        ["filtername"] = "player_bio",
        ["hammerid"] = 2906432,
        ["buttonid"] = 2906364,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_bio_temp",
    },
    {
        ["name"] = "Barrier Materia",
        ["shortname"] = "Barrier",
        ["filtername"] = "player_barrier",
        ["hammerid"] = 2906517,
        ["buttonid"] = 2906449,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_barrier_temp",
    },
    {
        ["name"] = "Ultima Materia",
        ["shortname"] = "Ultima",
        ["filtername"] = "player_ultima",
        ["hammerid"] = 2906602,
        ["buttonid"] = 2906534,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 20,
        ["pt_spawner"] = "item_ultima_temp",
    },
    {
        ["name"] = "Wind Materia",
        ["shortname"] = "Wind",
        ["filtername"] = "player_wind",
        ["hammerid"] = 2906834,
        ["buttonid"] = 2906766,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_wind_temp",
    },
    {
        ["name"] = "Heal Materia",
        ["shortname"] = "Heal",
        ["filtername"] = "player_heal",
        ["hammerid"] = 2907132,
        ["buttonid"] = 2907064,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_heal_temp",
    },
    {
        ["name"] = "Ice Materia",
        ["shortname"] = "Ice",
        ["filtername"] = "player_ice",
        ["hammerid"] = 2907354,
        ["buttonid"] = 2907286,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_ice_temp",
    },
    {
        ["name"] = "Aqua Materia",
        ["shortname"] = "Aqua",
        ["filtername"] = "player_water",
        ["hammerid"] = 2907705,
        ["buttonid"] = 2907637,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_water_temp",
    },
    {
        ["name"] = "Fire Materia",
        ["shortname"] = "Fire",
        ["filtername"] = "player_fire",
        ["hammerid"] = 2907860,
        ["buttonid"] = 2907792,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_fire_temp",
    },
    {
        ["name"] = "Electro Materia",
        ["shortname"] = "Electro",
        ["filtername"] = "player_electro",
        ["hammerid"] = 2908013,
        ["buttonid"] = 2907945,
        ["energyname"] = "item_electro_counter",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        --["hitmax"] = 1, -- DO NOT CHANGE: modified during stages
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_electro_temp",
    },
    {
        ["name"] = "Earth Materia",
        ["shortname"] = "Earth",
        ["filtername"] = "player_earth",
        ["hammerid"] = 2908100,
        ["buttonid"] = 2908032,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_earth_temp",
    },
    {
        ["name"] = "Gravity Materia",
        ["shortname"] = "Gravity",
        ["filtername"] = "player_gravity",
        ["hammerid"] = 2908185,
        ["buttonid"] = 2908117,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_gravity_temp",
    },
    {
        ["name"] = "Mimic Materia",
        ["shortname"] = "Mimic",
        ["filtername"] = "player_mimic",
        ["hammerid"] = 4525325,
        ["buttonid"] = 4525251,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "item_mimic_temp",
    },
}