return {
    {
        ["name"] = "Cube Materia",
        ["shortname"] = "Cube",
        ["filtername"] = "player_human_cube",
        ["hammerid"] = 481095,
        ["buttonid"] = 481114,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "human_cube_itemtemp",
    },
    {
        ["name"] = "Shield Materia",
        ["shortname"] = "Shield",
        ["filtername"] = "player_human_shield",
        ["hammerid"] = 481133,
        ["buttonid"] = 481121,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "human_shield_itemtemp",
    },
    {
        ["name"] = "Beam Materia",
        ["shortname"] = "Beam",
        ["filtername"] = "player_human_beam",
        ["hammerid"] = 481281,
        ["buttonid"] = 481278,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "human_beam_itemtemp",
    },
    {
        ["name"] = "Zombie Stars",
        ["shortname"] = "ZM Stars",
        ["filtername"] = "player_zombie_stars",
        ["hammerid"] = 479876,
        ["buttonid"] = 481359,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 45,
        ["pt_spawner"] = "zombie_stars_itemtemp",
    },
    {
        ["name"] = "Zombie Gravity",
        ["shortname"] = "ZM Gravity",
        ["filtername"] = "player_zombie_gravity",
        ["hammerid"] = 480499,
        ["buttonid"] = 480428,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 90,
        ["pt_spawner"] = "zombie_gravity_itemtemp",
    },
    {
        ["name"] = "Zombie Heal",
        ["shortname"] = "ZM Heal",
        ["filtername"] = "player_zombie_heal",
        ["hammerid"] = 480199,
        ["buttonid"] = 480575,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 50,
        ["pt_spawner"] = "zombie_heal_itemtemp",
    },
    {
        ["name"] = "Zombie Beam",
        ["shortname"] = "ZM Beam",
        ["filtername"] = "player_zombie_beam",
        ["hammerid"] = 480417,
        ["buttonid"] = 480201,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 50,
        ["pt_spawner"] = "zombie_beam_itemtemp",
    },
}