return {
    {
        ["name"] = "Rebel Chainsaw",
        ["shortname"] = "Chainsaw",
        ["hammerid"] = 645629,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
        ["pt_spawner"] = "weapon_saw_templ",
    },
    {
        ["name"] = "Pink Elephants",
        ["shortname"] = "Mines",
        ["filtername"] = "mineboom",
        ["hammerid"] = 643708,
        ["buttonid"] = 643710,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 5,
        ["cooldown"] = 2,
        --["energyname"] = "mine_limit",
        --["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        --["hitmax"] = 5, -- max uses
        ["pt_spawner"] = "mine_tele",
    },
    {
        ["name"] = "Ammo Box",
        ["shortname"] = "Ammo",
        ["filtername"] = "kuulid",
        ["hammerid"] = 594280,
        ["buttonid"] = 594273,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 2,
        ["cooldown"] = 60,
        --["energyname"] = "ammo_counter",
        --["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        --["hitmax"] = 2, -- max uses
        ["pt_spawner"] = "ammo_template",
    },
    {
        ["name"] = "Mountain Dew",
        ["shortname"] = "Heal",
        ["filtername"] = "Heal_Owner",
        ["hammerid"] = 310117,
        ["buttonid"] = 310114,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["maxuses"] = 2,
        ["cooldown"] = 10,
        ["pt_spawner"] = "Item_Heal_Temp",
    },
    {
        ["name"] = "Bubble Gun",
        ["shortname"] = "Bubble",
        ["filtername"] = "electric",
        ["hammerid"] = 309378,
        ["buttonid"] = 309380,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 55,
        ["pt_spawner"] = "item_electricmaker",
    },
    {
        ["name"] = "Rainbow Flamethrower",
        ["shortname"] = "Flamethrower",
        ["filtername"] = "flamethrower",
        ["hammerid"] = 312056,
        ["buttonid"] = 311975,
        ["energyname"] = "flame_counter",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMIN_REACHED,
        --["currentvalue"] = 20, -- in seconds (default: 20)
        ["pt_spawner"] = "flame_tele",
    },
    {
        ["name"] = "UFO",
        ["shortname"] = "UFO",
        ["filtername"] = "UFO_Owner",
        ["hammerid"] = 310976,
        ["buttonid"] = 310978,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 20,
        ["pt_spawner"] = "Item_UFO_Temp",
    },
}