return {
    {
        ["name"] = "Ammo",
        ["shortname"] = "Ammo",
        ["filtername"] = "player_ammo",
        ["hammerid"] = 431658,
        ["buttonid"] = 431660,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "ammo_temp",
    },
    {
        ["name"] = "Push",
        ["shortname"] = "Push",
        ["filtername"] = "player_wind",
        ["hammerid"] = 905720,
        ["buttonid"] = 905722,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "wind_temp",
    },
    {
        ["name"] = "Heal",
        ["shortname"] = "Heal",
        ["filtername"] = "player_heal",
        ["hammerid"] = 431583,
        ["buttonid"] = 431580,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "heal_temp",
    },
    {
        ["name"] = "Beam",
        ["shortname"] = "Beam",
        ["filtername"] = "player_beam",
        ["hammerid"] = 893904,
        ["buttonid"] = 893768,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "beam_temp",
    },
    { -- check
        ["name"] = "Slower Sphere",
        ["shortname"] = "Sphere",
        ["filtername"] = "player_poison",
        ["hammerid"] = 1157477,
        ["buttonid"] = 1157474,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "poison_temp",
    },
    {
        ["name"] = "Zombie Heal",
        ["shortname"] = "ZM Heal",
        ["filtername"] = "player_zheal",
        ["hammerid"] = 433324,
        ["buttonid"] = 433189,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 20,
        ["pt_spawner"] = "zheal_temp",
    },
    {
        ["name"] = "Zombie Gravity",
        ["shortname"] = "ZM Gravity",
        ["filtername"] = "player_zgravity",
        ["hammerid"] = 432888,
        ["buttonid"] = 432893,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 90,
        ["pt_spawner"] = "zgravity_temp",
    },
    {
        ["name"] = "l0v0l",
        ["shortname"] = "l0v0l",
        ["hammerid"] = 1046102,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
        ["pt_spawner"] = "l0v0l_temp",
    },
    {
        ["name"] = "Gravity Toilet",
        ["shortname"] = "Gravity",
        ["filtername"] = "player_gravityt",
        ["hammerid"] = 1355507,
        ["buttonid"] = 1355502,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "gravityt_temp",
    },
    {
        ["name"] = "Poison Toilet",
        ["shortname"] = "Poison",
        ["filtername"] = "player_poisont",
        ["hammerid"] = 1355429,
        ["buttonid"] = 1355424,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "poisont_temp",
    },
    {
        ["name"] = "Earth Toilet",
        ["shortname"] = "Earth",
        ["filtername"] = "player_eartht",
        ["hammerid"] = 1355587,
        ["buttonid"] = 1355584,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "eartht_temp",
    },
    {
        ["name"] = "Water Toilet",
        ["shortname"] = "Water",
        ["filtername"] = "player_watert",
        ["hammerid"] = 1355730,
        ["buttonid"] = 1355660,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "watert_temp",
    },
    {
        ["name"] = "Wind Toilet",
        ["shortname"] = "Wind",
        ["filtername"] = "player_pusht",
        ["hammerid"] = 1355879,
        ["buttonid"] = 1355874,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "pusht_temp",
    },
    {
        ["name"] = "Fire Toilet",
        ["shortname"] = "Fire",
        ["filtername"] = "player_firet",
        ["hammerid"] = 1355119,
        ["buttonid"] = 1355045,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "firet_temp",
    },
    {
        ["name"] = "Ice Toilet",
        ["shortname"] = "Ice",
        ["filtername"] = "player_icet",
        ["hammerid"] = 1355201,
        ["buttonid"] = 1355196,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "icet_temp",
    },
    {
        ["name"] = "Electric Toilet",
        ["shortname"] = "Electro",
        ["filtername"] = "player_elect",
        ["hammerid"] = 1355344,
        ["buttonid"] = 1355348,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "elect_temp",
    },
}