return {
    {
        ["name"] = "Sword",
        ["shortname"] = "Sword",
        ["hammerid"] = 13270,
        ["buttonid"] = 193544,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 45,
    },
    {
        ["name"] = "River Axe",
        ["shortname"] = "Axe",
        ["hammerid"] = 94227,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    {
        ["name"] = "Heal",
        ["shortname"] = "Heal",
        ["hammerid"] = 182215,
        ["buttonid"] = 182281,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
    },
    {
        ["name"] = "Steel",
        ["shortname"] = "Steel",
        ["hammerid"] = 515276,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    {
        ["name"] = "Flint",
        ["shortname"] = "Flint",
        ["hammerid"] = 515304,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    {
        ["name"] = "Firemines",
        ["shortname"] = "Firemines",
        ["hammerid"] = 948183,
        ["buttonid"] = 948192,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    {
        ["name"] = "Wall",
        ["shortname"] = "Wall",
        ["hammerid"] = 948269,
        ["buttonid"] = 948278,
        ["energyname"] = "item_block_counter",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        ["cooldown"] = 1,
        --["hitmax"] = 13, -- max uses
    },
    {
        ["name"] = "Dragon Egg",
        ["shortname"] = "Egg",
        ["hammerid"] = 1175908,
        ["buttonid"] = 1175905,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 5,
    },
    {
        ["name"] = "Torch",
        ["shortname"] = "Torch",
        ["hammerid"] = 1312275,
        ["buttonid"] = 1714938,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 2,
    },
    {
        ["name"] = "Torch",
        ["shortname"] = "Torch",
        ["hammerid"] = 1312443,
        ["buttonid"] = 1604876,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 2,
    },
    {
        ["name"] = "Bow And Arrows",
        ["shortname"] = "Bow",
        ["hammerid"] = 1657983,
        ["buttonid"] = 1657977,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 9,
    },
    {
        ["name"] = "Diamond Pickaxe",
        ["shortname"] = "Pickaxe",
        ["hammerid"] = 120494,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    -- алмаз и 9 редстоунов на 3 этапе
}