return {
    {
        ["name"] = "SpaceSuit",
        ["shortname"] = "SpaceSuit",
        ["hammerid"] = 2242,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    {
        ["name"] = "Fast Knife",
        ["shortname"] = "Fast Zombie",
        ["hammerid"] = 2342,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    {
        ["name"] = "Cisneros' Hero Burguer",
        ["shortname"] = "Burguer",
        ["filtername"] = "burg_pl",
        ["hammerid"] = 1905,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    {
        ["name"] = "Heal",
        ["shortname"] = "Heal",
        ["filtername"] = "heal",
        ["hammerid"] = 1984,
        ["buttonid"] = 1986,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 90,
    },
    {
        ["name"] = "Flamethrower",
        ["shortname"] = "Flamethrower",
        ["filtername"] = "we1",
        ["hammerid"] = 2091,
        ["buttonid"] = 1993,
        ["energyname"] = "ftlog2",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        --["hitmax"] = 40, -- seconds
    },
    {
        ["name"] = "PenisGun",
        ["shortname"] = "PenisGun",
        ["filtername"] = "penis",
        ["hammerid"] = 2618,
        ["buttonid"] = 2616,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 45,
    },
    {
        ["name"] = "Raivb1000 Prototype",
        ["shortname"] = "Raivb1000",
        ["filtername"] = "cannon",
        ["hammerid"] = 2841,
        ["buttonid"] = 2842,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 5,
    },
    {
        ["name"] = "Ammo Box",
        ["shortname"] = "Ammo",
        ["filtername"] = "ammo",
        ["hammerid"] = 2971,
        ["buttonid"] = 2972,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 90,
    },
    {
        ["name"] = "Mines",
        ["shortname"] = "Mines",
        ["hammerid"] = 3377,
        --["buttonid"] = 3378,
        ["mode"] = ENTWATCH_MODE_SPAM_PROTECTION_ONLY,
    },
    {
        ["name"] = "Mines",
        ["shortname"] = "Mines",
        ["hammerid"] = 3386,
        --["buttonid"] = 3387,
        ["mode"] = ENTWATCH_MODE_SPAM_PROTECTION_ONLY,
    },
    {
        ["name"] = "Rocket Launcher",
        ["shortname"] = "Rocket",
        ["filtername"] = "we2",
        ["hammerid"] = 3413,
        ["buttonid"] = 3437,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
    },
    {
        ["name"] = "CoolR Gun",
        ["shortname"] = "CoolR",
        ["filtername"] = "coolrguy",
        ["hammerid"] = 3504,
        ["buttonid"] = 3502,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
    },
    {
        ["name"] = "Speed Weapon",
        ["shortname"] = "Speed",
        ["hammerid"] = 3792,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    {
        ["name"] = "Tornado",
        ["shortname"] = "Tornado",
        ["filtername"] = "tornado",
        ["hammerid"] = 4047,
        ["buttonid"] = 4045,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 120,
    },
}