return {
    {
        ["name"] = "Scooby Snacks (Heal)",
        ["shortname"] = "Heal",
        ["filtername"] = "heal",
        ["hammerid"] = 870604,
        ["buttonid"] = 870614,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 180,
        ["pt_spawner"] = "template_heal",
    },
    {
        ["name"] = "Mines",
        ["shortname"] = "Mines",
        ["filtername"] = "Player_Mine",
        ["hammerid"] = 870493,
        ["buttonid"] = 870495,
        ["energyname"] = "item_mine_counter",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        --["hitmax"] = 5, -- max uses
        ["cooldown"] = 10,
        ["pt_spawner"] = "template_item_mine",
    },
    {
        ["name"] = "BFG",
        ["shortname"] = "BFG",
        ["filtername"] = "bfg_user",
        ["hammerid"] = 870617,
        ["buttonid"] = 870949,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 180,
        ["pt_spawner"] = "bfg_template",
    },
    {
        ["name"] = "Machine Gun",
        ["shortname"] = "Machine Gun",
        ["filtername"] = "mg_user",
        ["hammerid"] = 870657,
        ["buttonid"] = 870654,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 180,
        ["pt_spawner"] = "raph_item_mg",
    },
    {
        ["name"] = "Old Age",
        ["shortname"] = "Old Age",
        ["filtername"] = "hich_item_tw_user",
        ["hammerid"] = 871026,
        ["buttonid"] = 871032,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 120,
        ["pt_spawner"] = "hich_item_tw_template",
    },
    {
        ["name"] = "Transparent",
        ["shortname"] = "Transparent",
        ["filtername"] = "hich_item_cd_user",
        ["hammerid"] = 870820,
        ["buttonid"] = 870824,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 30,
        ["pt_spawner"] = "hich_item_cd_template",
    },
    {
        ["name"] = "Ban Hammer",
        ["shortname"] = "Ban Hammer",
        ["filtername"] = "hich_item_bh_user",
        ["hammerid"] = 870972,
        ["buttonid"] = 870967,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "hich_item_bh_template",
    },

    {
        ["name"] = "Zombie Pull Force",
        ["shortname"] = "ZM Pull",
        ["filtername"] = "hich_item_zh_user",
        ["hammerid"] = 870797,
        ["buttonid"] = 870804,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 30,
        ["pt_spawner"] = "hich_item_zh_template",
    },
    {
        ["name"] = "Zombie Magic Cylinder",
        ["shortname"] = "ZM Cylinder",
        ["filtername"] = "hich_item_mc_user",
        ["hammerid"] = 871084,
        ["buttonid"] = 871086,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 45,
        ["pt_spawner"] = "hich_item_mc_makertemp",
    },
    {
        ["name"] = "Zombie Non Euclidian",
        ["shortname"] = "ZM Non Euclidian",
        ["filtername"] = "hich_item_zmtper_user",
        ["hammerid"] = 871189,
        ["buttonid"] = 871184,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 30,
        ["pt_spawner"] = "hich_item_zmtper_template",
    },
    {
        ["name"] = "Zombie For Frodo",
        ["shortname"] = "ZM Frodo",
        ["filtername"] = "frodo_user",
        ["hammerid"] = 870406,
        ["buttonid"] = 870413,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 120,
        ["pt_spawner"] = "raph_item_frodo",
    },
}