return {
    -- Secret weapon #1: stage3 Serious_secret_start_relay
    -- Secret weapon #2: stage2 Nuke_secret_start_relay
    {
        ["name"] = "Black Dragon",
        ["shortname"] = "Dragon",
        ["filtername"] = "Black_Dragon_Owner",
        ["hammerid"] = 922726,
        ["buttonid"] = 922730,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
    },
    {
        ["name"] = "Tactical Nuke",
        ["shortname"] = "Nuke",
        ["filtername"] = "Nuke_Owner",
        ["hammerid"] = 904710,
        ["buttonid"] = 904705,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 10,
        ["pt_spawner"] = "Weapon_Nuke_Temp",
    },
    {
        ["name"] = "Blizzard Desert Eagle",
        ["shortname"] = "Deagle",
        ["filtername"] = "Ice_Deagle_Owner",
        ["hammerid"] = 886282,
        ["buttonid"] = 886284,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["pt_spawner"] = "Weapon_Ice_Deagle_Temp",
    },
    {
        ["name"] = "M200 Intervention",
        ["shortname"] = "M200",
        ["filtername"] = "M200_Owner",
        ["hammerid"] = 888923,
        ["buttonid"] = 888853,
        ["energyname"] = "Item_M200_counter",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        ["hitmax"] = 5, -- max uses
        ["cooldown"] = 8,
        ["pt_spawner"] = "Weapon_M200_Temp",
    },
    {
        ["name"] = "Serious Bomb",
        ["shortname"] = "Bomb",
        ["filtername"] = "Serious_Bomb_Owner",
        ["hammerid"] = 870902,
        ["buttonid"] = 870897,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 15,
        ["pt_spawner"] = "Weapon_Serious_Bomb_Temp",
    },
    {
        ["name"] = "Mountain Dew",
        ["shortname"] = "MTN Dew",
        ["filtername"] = "mtn_Owner",
        ["hammerid"] = 828603,
        ["buttonid"] = 828528,
        ["energyname"] = "Item_mtn_counter",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        ["hitmax"] = 2, -- max uses
        ["cooldown"] = 80,
        ["pt_spawner"] = "Weapon_mtn_Temp",
    },
    {
        ["name"] = "Small Mountain Dew",
        ["shortname"] = "Small MTN Dew",
        ["filtername"] = "mtnS_Owner",
        ["hammerid"] = 829356,
        ["buttonid"] = 829281,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["pt_spawner"] = "Weapon_mtnS_Temp",
    },
    {
        ["name"] = "Auto Shotgun",
        ["shortname"] = "Shotgun",
        ["filtername"] = "Shotgun_Owner",
        ["hammerid"] = 830269,
        ["buttonid"] = 830262,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["pt_spawner"] = "Weapon_Shotgun_Temp",
    },
    {
        ["name"] = "Serious Saw",
        ["shortname"] = "Saw",
        ["hammerid"] = 831403,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
        ["pt_spawner"] = "Weapon_saw_Temp",
    },
    {
        ["name"] = "Small Doritos Crisps",
        ["shortname"] = "Small Doritos",
        ["filtername"] = "doritosS_Owner",
        ["hammerid"] = 832705,
        ["buttonid"] = 832696,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 75,
        ["pt_spawner"] = "Weapon_doritosS_Temp",
    },
    {
        ["name"] = "Assault Rifle",
        ["shortname"] = "M4",
        ["filtername"] = "m4_Owner",
        ["hammerid"] = 764704,
        ["buttonid"] = 764699,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "Weapon_m4_Temp",
    },
    {
        ["name"] = "Pack Of Doritos",
        ["shortname"] = "Doritos",
        ["filtername"] = "doritos_Owner",
        ["hammerid"] = 767144,
        ["buttonid"] = 767148,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 95,
        ["pt_spawner"] = "Weapon_doritos_Temp",
    },
    {
        ["name"] = "Hand Cannon",
        ["shortname"] = "Cannon",
        ["filtername"] = "cannon_Owner",
        ["hammerid"] = 715735,
        ["buttonid"] = 715732,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 135,
        ["pt_spawner"] = "Weapon_cannon_Temp",
    },
    {
        ["name"] = "Paper AWP",
        ["shortname"] = "AWP",
        ["filtername"] = "Paper_AWP_Owner",
        ["hammerid"] = 1023156,
        ["buttonid"] = 1023151,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 80,
        ["pt_spawner"] = "Weapon_Paper_AWP_Temp",
    },
    {
        ["name"] = "Serious Backpack",
        ["shortname"] = "Backpack",
        ["filtername"] = "backpack_Owner",
        ["hammerid"] = 1297131,
        ["buttonid"] = 1297126,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["pt_spawner"] = "Weapon_backpack_Temp",
    },
    {
        ["name"] = "Gersch Device",
        ["shortname"] = "Device",
        ["filtername"] = "gersch_Owner",
        ["hammerid"] = 1245325,
        ["buttonid"] = 1245307,
        ["energyname"] = "Item_gersch_counter",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        ["hitmax"] = 3, -- max uses
        ["cooldown"] = 1,
        ["pt_spawner"] = "Weapon_gersch_Temp",
    },
    {
        ["name"] = "Raygun",
        ["shortname"] = "Raygun",
        ["filtername"] = "raygun_Owner",
        ["hammerid"] = 1229802,
        ["buttonid"] = 1229804,
        ["energyname"] = "Item_raygun_counter",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        ["hitmax"] = 12, -- max uses
        ["cooldown"] = 5,
        ["pt_spawner"] = "Weapon_raygun_Temp",
    },
    {
        ["name"] = "Wunderwaffe",
        ["shortname"] = "Wunderwaffe",
        ["filtername"] = "wunderwaffe_Owner",
        ["hammerid"] = 1231087,
        ["buttonid"] = 1231075,
        ["energyname"] = "Item_wunderwaffe_counter",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        ["hitmax"] = 3, -- max uses
        ["cooldown"] = 70,
        ["pt_spawner"] = "Weapon_wunderwaffe_Temp",
    },
    {
        ["name"] = "Thundergun",
        ["shortname"] = "Thundergun",
        ["filtername"] = "thunder_Owner",
        ["hammerid"] = 1215169,
        ["buttonid"] = 1215179,
        ["energyname"] = "Item_thunder_counter",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMAX_REACHED,
        ["hitmax"] = 2, -- max uses
        ["cooldown"] = 3,
        ["pt_spawner"] = "Weapon_thunder_Temp",
    },
    {
        ["name"] = "Bowie Knife",
        ["shortname"] = "Bowie",
        ["filtername"] = "bowie_Owner",
        ["hammerid"] = 1215981,
        ["buttonid"] = 1215974,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "Weapon_bowie_Temp",
    },
    {
        ["name"] = "Hammer",
        ["shortname"] = "Hammer",
        ["hammerid"] = 1216082,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    {
        ["name"] = "Nide Autism",
        ["shortname"] = "Nide",
        ["hammerid"] = 1757351,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },

    -- ZM Materias
    {
        ["name"] = "Stamina-Up",
        ["shortname"] = "Stamina",
        ["filtername"] = "Stamina_Up_Owner",
        ["hammerid"] = 916231,
        ["buttonid"] = 916224,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["pt_spawner"] = "Weapon_Stamina_Up_Temp",
    },
    {
        ["name"] = "Electric Cherry",
        ["shortname"] = "Cherry",
        ["filtername"] = "electric cherry_Owner",
        ["hammerid"] = 1109544,
        ["buttonid"] = 1109469,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 80,
        ["pt_spawner"] = "Weapon_electric cherry_Temp",
    },
    {
        ["name"] = "PHD Flopper",
        ["shortname"] = "PHD",
        ["filtername"] = "phd_flopper_Owner",
        ["hammerid"] = 1089971,
        ["buttonid"] = 1089958,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 85,
        ["pt_spawner"] = "Weapon_phd_flopper_Temp",
    },
    {
        ["name"] = "Deadshot",
        ["shortname"] = "Deadshot",
        ["filtername"] = "deadshot_Owner",
        ["hammerid"] = 1280242,
        ["buttonid"] = 1280167,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["pt_spawner"] = "Weapon_deadshot_Temp",
    },
}