return {
    {
        ["name"] = "Fumo Yuuka",
        ["shortname"] = "Fumo Yuuka",
        ["hammerid"] = 2540603,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    {
        ["name"] = "Fumo Sakyua",
        ["shortname"] = "Fumo Sakyua",
        ["hammerid"] = 2540884,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    {
        ["name"] = "Fumo Cirno",
        ["shortname"] = "Fumo Cirno",
        ["hammerid"] = 2541078,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    {
        ["name"] = "Fumo Flandre",
        ["shortname"] = "Fumo Flandre",
        ["hammerid"] = 2541142,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    {
        ["name"] = "Fumo Reimu",
        ["shortname"] = "Fumo Reimu",
        ["hammerid"] = 2541150,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    {
        ["name"] = "Fumo Remilia",
        ["shortname"] = "Fumo Remilia",
        ["hammerid"] = 2541158,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },
    {
        ["name"] = "Zombie Corona",
        ["shortname"] = "ZM Corona",
        ["filtername"] = "itemholdergsb_corona",
        ["hammerid"] = 2719246,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
        ["pt_spawner"] = "template_gsboss_itemcorona",
    },
    {
        ["name"] = "Zombie Wave Rider",
        ["shortname"] = "ZM Wave Rider",
        ["filtername"] = "player_item_zm_waverider",
        ["hammerid"] = 3744675,
        ["buttonid"] = 3744671,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 80,
        ["pt_spawner"] = "template_item_zm_waverider",
    },
    --[[{
        ["name"] = "Zombie Permanent Monsoon",
        ["shortname"] = "ZM Monsoon",
        ["hammerid"] = 2617226,
        ["buttonclass"] = "game_ui",
        ["buttonid"] = 2486230,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
    },--]]
    {
        ["name"] = "Zombie Toss",
        ["shortname"] = "ZM Toss",
        ["filtername"] = "player_item_zm_toss",
        ["hammerid"] = 3225926,
        ["buttonid"] = 3225928,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "template_item_toss",
    },
    {
        ["name"] = "Zombie Coronavirus Minion",
        ["shortname"] = "ZM Minion",
        ["filtername"] = "itemholdergsb_minion",
        ["hammerid"] = 2717659,
        ["buttonid"] = 2717483,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 5,
        ["pt_spawner"] = "template_gsboss_itemminion",
    },
    {
        ["name"] = "Warp",
        ["shortname"] = "Warp",
        ["filtername"] = "itemholdergsb_hewarp",
        ["hammerid"] = 2718346,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
        ["pt_spawner"] = "template_gsboss_itemhewarp",
    },
    {
        ["name"] = "Zombie Shadow Hand",
        ["shortname"] = "ZM Shadow Hand",
        ["filtername"] = "player_item_zm_shadowhand",
        ["hammerid"] = 3530793,
        ["buttonid"] = 3530924,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 50,
        ["pt_spawner"] = "template_item_shadowhand",
    },
    {
        ["name"] = "Spellcard",
        ["shortname"] = "Spellcard",
        ["filtername"] = "player_item_ct_familiar",
        ["hammerid"] = 3691869,
        ["buttonid"] = 3691871,
        ["energyname"] = "item_familiar_spellcard_counter",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMIN_REACHED,
        --["currentvalue"] = 2, -- max uses
        ["cooldown"] = 10,
        ["pt_spawner"] = "template_item_familiar",
    },
    {
        ["name"] = "Wavewall",
        ["shortname"] = "Wavewall",
        ["filtername"] = "player_wavewall",
        ["hammerid"] = 3743966,
        ["buttonid"] = 3743968,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 120,
        ["pt_spawner"] = "template_item_ct_wavewall",
    },
    {
        ["name"] = "Boomerang",
        ["shortname"] = "Boomerang",
        ["filtername"] = "player_item_ct_boomerang",
        ["hammerid"] = 3225872,
        ["buttonid"] = 3225874,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 45,
        ["pt_spawner"] = "template_item_boomerang",
    },
    {
        ["name"] = "SB",
        ["shortname"] = "SB",
        ["filtername"] = "itemholdergsb_blocker",
        ["hammerid"] = 1936625,
        ["buttonid"] = 1936634,
        ["energyname"] = "itemgsb_blocker_counter",
        ["mode"] = ENTWATCH_MODE_COUNTER_FMIN_REACHED,
        --["currentvalue"] = 3, -- max uses
        ["cooldown"] = 5,
        ["pt_spawner"] = "itemgsb_template",
    },
    {
        ["name"] = "Grenade Hoop",
        ["shortname"] = "Hoop",
        ["filtername"] = "player_item_ct_berke3",
        ["hammerid"] = 3206401,
        ["buttonid"] = 3206403,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 180,
        ["pt_spawner"] = "berkeitemtemplate3",
    },
    {
        ["name"] = "Melon Launcher",
        ["shortname"] = "Melon",
        ["filtername"] = "player_item_ct_berke2",
        ["hammerid"] = 3206375,
        ["buttonid"] = 3206381,
        ["mode"] = ENTWATCH_MODE_SPAM_PROTECTION_ONLY,
        ["pt_spawner"] = "berkeitemtemplate2",
    },
    {
        ["name"] = "Spin Round",
        ["shortname"] = "Spin",
        ["filtername"] = "player_item_ct_berke1",
        ["hammerid"] = 3206312,
        ["buttonid"] = 3206321,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 150,
        ["pt_spawner"] = "berkeitemtemplate1",
    },
    {
        ["name"] = "Grimoire",
        ["shortname"] = "Grimoire",
        ["hammerid"] = 3216321,
        ["mode"] = ENTWATCH_MODE_NOBUTTON,
        ["pt_spawner"] = "template_item_grimoire",
    },
    {
        ["name"] = "Shotgun",
        ["shortname"] = "Shotgun",
        ["hammerid"] = 3673942,
        ["mode"] = ENTWATCH_MODE_SPAM_PROTECTION_ONLY,
        ["pt_spawner"] = "template_item_shotgun",
    },
}