return {
    {
        ["name"] = "Ammo",
        ["shortname"] = "Ammo",
        ["filtername"] = "player_ammo",
        ["hammerid"] = 565799,
        ["buttonid"] = 565646,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "ammo_itemtemp",
    },
    {
        ["name"] = "Killer",
        ["shortname"] = "Killer",
        ["filtername"] = "player_killer",
        ["hammerid"] = 565801,
        ["buttonid"] = 565789,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 20,
        ["pt_spawner"] = "killer_itemtemp",
    },
    {
        ["name"] = "Hedge",
        ["shortname"] = "Hedge",
        ["filtername"] = "player_hedge",
        ["hammerid"] = 565893,
        ["buttonid"] = 565895,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "hedge_itemtemp",
    },
    {
        ["name"] = "Push",
        ["shortname"] = "Push",
        ["filtername"] = "player_push",
        ["hammerid"] = 566048,
        ["buttonid"] = 566050,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "push_itemtemp",
    },
    {
        ["name"] = "Heal",
        ["shortname"] = "Heal",
        ["filtername"] = "player_heal",
        ["hammerid"] = 566342,
        ["buttonid"] = 566271,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "heal_itemtemp",
    },
    {
        ["name"] = "Gravity",
        ["shortname"] = "Gravity",
        ["filtername"] = "player_gravity",
        ["hammerid"] = 2289102,
        ["buttonid"] = 566639,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "gravity_itemtemp",
    },
    {
        ["name"] = "Fire",
        ["shortname"] = "Fire",
        ["filtername"] = "player_fire",
        ["hammerid"] = 566646,
        ["buttonid"] = 566560,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "fire_itemtemp",
    },
    {
        ["name"] = "Ice",
        ["shortname"] = "Ice",
        ["filtername"] = "player_ice",
        ["hammerid"] = 566648,
        ["buttonid"] = 566417,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "ice_itemtemp",
    },
    {
        ["name"] = "Lightning",
        ["shortname"] = "Lightning",
        ["filtername"] = "player_lightning",
        ["hammerid"] = 566650,
        ["buttonid"] = 566118,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "lightning_itemtemp",
    },
    {
        ["name"] = "Zombie Killer",
        ["shortname"] = "ZM Killer",
        ["filtername"] = "player_zkiller",
        ["hammerid"] = 566669,
        ["buttonid"] = 566804,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 120,
        ["pt_spawner"] = "zkiller_itemtemp",
    },
    {
        ["name"] = "Zombie Heal",
        ["shortname"] = "ZM Heal",
        ["filtername"] = "player_zheal",
        ["hammerid"] = 566812,
        ["buttonid"] = 566947,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 20,
        ["pt_spawner"] = "zheal_itemtemp",
    },
    {
        ["name"] = "Zombie Fire",
        ["shortname"] = "ZM Fire",
        ["filtername"] = "player_zfire",
        ["hammerid"] = 567096,
        ["buttonid"] = 566961,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 90,
        ["pt_spawner"] = "zfire_itemtemp",
    },
    {
        ["name"] = "Zombie Drug",
        ["shortname"] = "ZM Drug",
        ["filtername"] = "player_zdrag",
        ["hammerid"] = 567263,
        ["buttonid"] = 567398,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 90,
        ["pt_spawner"] = "zdrag_itemtemp",
    },
    {
        ["name"] = "Zombie Invisible",
        ["shortname"] = "ZM Invisible",
        ["filtername"] = "player_zinv",
        ["hammerid"] = 567408,
        ["buttonid"] = 567478,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 90,
        ["pt_spawner"] = "zinv_itemtemp",
    },
    {
        ["name"] = "Zombie Poison",
        ["shortname"] = "ZM Poison",
        ["filtername"] = "player_zpoison",
        ["hammerid"] = 567548,
        ["buttonid"] = 567553,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 90,
        ["pt_spawner"] = "zpoison_itemtemp",
    },
    {
        ["name"] = "Zombie Gravity",
        ["shortname"] = "ZM Gravity",
        ["filtername"] = "player_zgravity",
        ["hammerid"] = 567631,
        ["buttonid"] = 567192,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 90,
        ["pt_spawner"] = "zgravity_itemtemp",
    },
}