return {
    {
        ["name"] = "Katon",
        ["shortname"] = "Katon",
        ["filtername"] = "player_katon",
        ["hammerid"] = 2030183,
        ["buttonid"] = 2030113,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 35,
        ["pt_spawner"] = "katon_itemtemp",
    },
    {
        ["name"] = "Raiton",
        ["shortname"] = "Raiton",
        ["filtername"] = "player_raiton",
        ["hammerid"] = 2030357,
        ["buttonid"] = 2030363,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "raiton_itemtemp",
    },
    {
        ["name"] = "Futon",
        ["shortname"] = "Futon",
        ["filtername"] = "player_futon",
        ["hammerid"] = 2030570,
        ["buttonid"] = 2030637,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "futon_itemtemp",
    },
    {
        ["name"] = "Suiton",
        ["shortname"] = "Suiton",
        ["filtername"] = "player_suiton",
        ["hammerid"] = 2030744,
        ["buttonid"] = 2030669,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "suiton_itemtemp",
    },
    {
        ["name"] = "Chakra",
        ["shortname"] = "Chakra",
        ["filtername"] = "player_heal",
        ["hammerid"] = 2030956,
        ["buttonid"] = 2030821,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "heal_itemtemp",
    },
    {
        ["name"] = "Doton",
        ["shortname"] = "Doton",
        ["filtername"] = "player_doton",
        ["hammerid"] = 2030973,
        ["buttonid"] = 2030984,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 65,
        ["pt_spawner"] = "doton_itemtemp",
    },
    {
        ["name"] = "Goju rashomon",
        ["shortname"] = "Rashomon",
        ["filtername"] = "player_rashomon",
        ["hammerid"] = 2031931,
        ["buttonid"] = 2031937,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 12,
        ["pt_spawner"] = "rashomon_itemtemp",
    },
    {
        ["name"] = "Mokuton kajukai korin",
        ["shortname"] = "Mokuton",
        ["filtername"] = "player_kajukai_korin",
        ["hammerid"] = 2032010,
        ["buttonid"] = 2032016,
        ["mode"] = ENTWATCH_MODE_LIMITED_USES,
        ["cooldown"] = 10,
        ["pt_spawner"] = "kajukai_korin_itemtemp",
    },
    {
        ["name"] = "Zombie Madara",
        ["shortname"] = "ZM Madara",
        ["filtername"] = "player_zmadara",
        ["hammerid"] = 2032092,
        ["buttonid"] = 2032086,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 160,
        ["pt_spawner"] = "zmadara_itemtemp",
    },
    {
        ["name"] = "Zombie Rinnegan",
        ["shortname"] = "ZM Rinnegan",
        ["filtername"] = "player_zheal",
        ["hammerid"] = 2031063,
        ["buttonid"] = 2031057,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 50, -- 5
        ["pt_spawner"] = "zheal_itemtemp",
    },
    {
        ["name"] = "Zombie Kaleidoscope",
        ["shortname"] = "ZM Kaleidoscope",
        ["filtername"] = "player_zkaleidoscope",
        ["hammerid"] = 2031274,
        ["buttonid"] = 2031204,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 70,
        ["pt_spawner"] = "zkaleidoscope_itemtemp",
    },
    {
        ["name"] = "Zombie Amaterasu",
        ["shortname"] = "ZM Amaterasu",
        ["filtername"] = "player_zamateratsu",
        ["hammerid"] = 2031573,
        ["buttonid"] = 2031440,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 60,
        ["pt_spawner"] = "Temp_zamateratsu",
    },
    {
        ["name"] = "Zombie Sharingan",
        ["shortname"] = "ZM Sharingan",
        ["filtername"] = "player_zsharingan",
        ["hammerid"] = 2031677,
        ["buttonid"] = 2031746,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 90,
        ["pt_spawner"] = "zsharingan_itemtemp",
    },
    {
        ["name"] = "Zombie Genjutsu",
        ["shortname"] = "ZM Genjutsu",
        ["filtername"] = "player_zgenjutsu",
        ["hammerid"] = 2031785,
        ["buttonid"] = 2031779,
        ["mode"] = ENTWATCH_MODE_COOLDOWNS,
        ["cooldown"] = 50,
        ["pt_spawner"] = "zgenjutsu_itemtemp",
    },
}